=== lai-tran-the-vinh/thuc-hanh-cong-nghe-xml-va-ung-dung/Buoi2/Bai2/sinhvien.dtd
<!ELEMENT class (student*)>
<!ELEMENT student (name, subjects)>
<!ATTLIST student id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT subjects (subject+)>
<!ELEMENT subject (subject_name, score)>
<!ELEMENT subject_name (#PCDATA)>
<!ELEMENT score (#PCDATA)>

=== lai-tran-the-vinh/thuc-hanh-cong-nghe-xml-va-ung-dung/Buoi1/Bai2/sinhvien.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE class SYSTEM "../../Buoi2/Bai2/sinhvien.dtd">

<class>
    <student id="SV001">
        <name>Nguyen Van A</name>
        <subjects>
            <subject>
                <subject_name>Mathematics</subject_name>
                <score>9.0</score>
            </subject>
            <subject>
                <subject_name>Enghlish</subject_name>
                <score>9.5</score>
            </subject>
        </subjects>
    </student>
    <student id="SV002">
        <name>Tran Thi B</name>
        <subjects>
            <subject>
                <subject_name>Mathematics</subject_name>
                <score>8.0</score>
            </subject>
            <subject>
                <subject_name>Enghlish</subject_name>
                <score>8.5</score>
            </subject>
        </subjects>
    </student>
</class>
