=== lai-tran-the-vinh/thuc-hanh-cong-nghe-xml-va-ung-dung/Buoi2/Bai1.3/donhang.dtd
<!ELEMENT company (order*)>
<!ELEMENT order (products)>
<!ATTLIST order id CDATA #REQUIRED>
<!ELEMENT products (product+)>
<!ELEMENT product (name, quantity)>
<!ATTLIST product id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== lai-tran-the-vinh/thuc-hanh-cong-nghe-xml-va-ung-dung/Buoi2/Bai1.3/donhang.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE company SYSTEM "donhang.dtd"> -->

<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../Buoi3/Bai2/Bai2.3/donhang.xsd">
    <order id="O001">
        <products>
            <product id="P001">
                <name>Kem tron Thai Lan</name>
                <quantity>10</quantity>
            </product>
            <product id="P002">
                <name>Kem chong nang</name>
                <quantity>15</quantity>
            </product>
        </products>
    </order>

    <order id="O002">
        <products>
            <product id="P003">
                <name>Mit say</name>
                <quantity>25</quantity>
            </product>
            <product id="P004">
                <name>Banh Oreo</name>
                <quantity>20</quantity>
            </product>
        </products>
    </order>
</company>
